spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db_girl?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  http:
    multipart:
      max-file-size: 128KB
      max-request-size: 128KB
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/db_girl
  activemq:
#    broker-url: tcp://127.0.0.1:61616

logging:
  level:
    com: DEBUG

# mybatis配置
#mybatis:
#  type-aliases-package: com.immoc.girl.core.domain