spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db_girl?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  http:
    multipart:
      max-file-size: 128KB
      max-request-size: 128KB
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/db_girl
  activemq:
#    broker-url: tcp://127.0.0.1:61616
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 12345678
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 8
      # 连接池中的最大空闲连接
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
    timeout: 0


logging:
  path:
  level:
    com.imooc: DEBUG
    org.springframework.web: INFO
    org.hibernate: ERROR


# spring-boot集成mybatis
# http://www.ityouknow.com/springboot/2016/11/06/springboot(%E5%85%AD)-%E5%A6%82%E4%BD%95%E4%BC%98%E9%9B%85%E7%9A%84%E4%BD%BF%E7%94%A8mybatis.html

# 1.注解方式 @MapperScan("com.xxx.mapper") @Select @Result @Insert @Update @Delete

# 2.xm方式 项目配置mybatis.mapper-locations=classpath:mybatis/mapper/*.xml
mybatis:
  mapper-locations: classpath:mapper/*.xml
